### ISSUE TITLE
Vanced dosent support one ui 3 (android 11)

### ISSUE THREAD

**Issue by Batu145** [YTVanced/SponsorBlock#10]
I updated my samsung galaxy s20 to one ui 3 and after reboot my youtube vanced disappear.

1. Try to install again showing error: there was a problem parsing the package
2. Uninstall microg and reinstall works fine with youtube vanced music
3. Using sai installer, gets me the same problem as 1st one 
4. With vanced manager i got an error saying: Error
Installation failed because of the app conflicts with an already installed app. Uninstall the current version of the app then try again.

Advance:
INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.vanced.android.youtube signatures do not mach previously installed version: ignoring!

If you ask me i think youtube vanced dosent support one ui 3 i think you need to updated it and i saw some more guys having same issue when i was searching about it. And i asked your support group about help they tryed everything but it didint work. And somehow i can download youtube music vanced but not youtube vanced. My microg everything works fine but my youtube vanced is not working. Also its [Non ROOT]

![Screenshot_20210108-040504_Vanced Manager](https://user-images.githubusercontent.com/48372209/103970040-98aeb580-5167-11eb-8e87-86db547e93b7.jpg)
![Screenshot_20210108-040508_Vanced Manager](https://user-images.githubusercontent.com/48372209/103970043-99474c00-5167-11eb-8e54-015898ae62b3.jpg)
![Screenshot_20210108-040649_One UI Home](https://user-images.githubusercontent.com/48372209/103970046-99dfe280-5167-11eb-9045-a0350bb4da5f.jpg)
![Screenshot_20210108-040744_Finder](https://user-images.githubusercontent.com/48372209/103970048-9a787900-5167-11eb-8f91-e943b32df379.jpg)
![Screenshot_20210108-040914_Settings](https://user-images.githubusercontent.com/48372209/103970050-9b110f80-5167-11eb-962d-f4749703af37.jpg)

**Comment by KevinX8** [comment]
This is sponsorblock? Why are you reporting oneui issues to vanced anyways they should go to Samsung
