### ISSUE TITLE
Tabs and group tabs like in chrome app

### ISSUE THREAD

**Issue by ValeriyBlyus** [YTVanced/SponsorBlock#13]
An idea how to make the app better and more useful.
Like in chrome app[Chrome app](https://play.google.com/store/apps/details?id=com.android.chrome) 
To make the functionality of creating different tabs and group tabs in different incstance. This functionality can make this application more great that nowadays. IMHO.
And thanks for this beautiful app.

**Comment by KevinX8** [comment]
wrong repo
