### ISSUE TITLE
Edit and correct reported false sponsor block

### ISSUE THREAD

**Issue by KyleBroflowski** [YTVanced/SponsorBlock#16]
I saw a video uploaded 3mins ago and it already had a long falsely marked segment with sponsor blocked content. It automatically skipped according to my settings. So when I tried to edit it, there wasn't an option to flag a false sponsor block.
Link to video: https://youtu.be/ENqgbQATjLw

**Comment by KevinX8** [comment]
downvoting segments is planned to be added eventually to the vanced implementation, for now just report the segment using your PC or the sponsoblock discord https://discord.gg/QnmVMpU
