### ISSUE TITLE
[Feature Request]Sudden loud noises block

### ISSUE THREAD

**Issue by Aster971** [YTVanced/SponsorBlock#29]
Quite a few youtube channels have extremely loud and annoying segments in the middle if a video that adds no value to user experience other than annoyance so if possible could that be implemented into sponsor block?

**Comment by caneleex** [comment]
this repo is just the vanced implementation of SponsorBlock. open an issue in the official [SponsorBlock repo](https://github.com/ajayyy/SponsorBlock)
