### ISSUE TITLE
[Feature Request] Show Updated Time For SponsorBlock

### ISSUE THREAD

**Issue by nochlab1** [YTVanced/SponsorBlock#33]
On SponsorBlock on PC it shows updated time in prentices is it able to be added
Thanks
![119600148-71722100-bdb4-11eb-8f17-ed0d1f04cde7](https://user-images.githubusercontent.com/37608994/120560123-35504900-c3d0-11eb-83a9-3aff3c39f22c.jpg)

**Comment by caneleex** [comment]
this feature has been added and will be out with the next vanced release.
