### ISSUE TITLE
[Bug] SponsorBlock Skip segment not working  - caused by Youtube shorts

### ISSUE THREAD

**Issue by botetta** [YTVanced/SponsorBlock#36]
**Bug description**
I have made a [previous post](https://github.com/YTVanced/Vanced/issues/753)  about how the Skip segment button wasn't appearing sometimes in YouTube vanced. 

I thought it was random, but since then, I have found out the exact cause of the issue. I added a comment there, but since that issue is now closed, I wanted to make a new report so I can make sure it is seen. 

Basically, watching a YouTube short causes several features of sponsorblock to stop working, for example the skip segment button stops appearing, or the add new segment button stops working. (these are the ones I've found, there might be other things that break) 

See steps to reproduce for details. 

**Variant**
Non-Root

**Vanced version**
16.20.35

**Android version**
Android 11 

**Device**
OnePlus 8T

**Steps to Reproduce**
1. Open youtube vanced, make sure that the options for different segments are set to show skip button in the sponsorblock settings. 
2. Click on any number of regular YouTube videos with skippable segments in them, they should work without issues. 
3. Now watch one YouTube Short 
4. After this, the skip segment button will no longer appear on any regular YouTube videos, and the add new segment button stops working, if it is enabled.
5. You can only fix this by restarting the app, but the issue comes back every time you watch one YouTube short. 

**Expected behavior**
Skip segment button should always appear when it needs to, regardless of watching YouTube shorts.

**Comment by KevinX8** [comment]
done

**Comment by caneleex** [comment]
This issue has been fixed, however I'm going to reopen this issue until a new Vanced release is out with the fix

**Comment by caneleex** [comment]
a new Vanced release with the fix is out.
