### ISSUE TITLE
Allow to block/flag seducing contents for people who don't watch porn

### ISSUE THREAD

**Issue by Nadim748** [YTVanced/SponsorBlock#41]
Add an option to block any seducing content so that people who have quit or want to quit porn  don't see it. It is really hard not to watch it once it is in front of you. Specially for people who want to quit porn. This type of content redirects us to porn websites. Just add an option so that anyone can flag this content and after a certain numbers of flags it gets blocked for users who choose to do so it.  It is really helpfull for everyone. 
And you know how hard it is to stop porn addiction. Even the people who know it is ruining them cant stop it. 
People who are porn addict and dont have any problem with it might think that this is not a BIG problem but please think about others also. Its a problem and I know that.

And I want to thank you very much for removing those ads from youtube (that tiktok ads that are meant to make you horny). I have stopped watching porn after downloading youtube vanced.

 

>

**Comment by caneleex** [comment]
if you'd like to see such category in SponsorBlock, open an issue in the [SponsorBlock repo](https://github.com/ajayyy/SponsorBlock/issues/new) or join the [SponsorBlock discord](https://discord.gg/sponsorblock) to talk about this new category in [#new-category-discussion](https://canary.discord.com/channels/603643120093233162/650803943152156673).

this is a repository for the YouTube Vanced implementation, general ideas for SponsorBlock don't belong here
