### ISSUE TITLE
It stops working after a while 

### ISSUE THREAD

**Issue by Sneffel** [YTVanced/SponsorBlock#43]
I don't know if stops after some vids, after some time or what else, but after a while it just stops working. 
I need to really close the app with the X and reopen it to make it work. 
Can somebody fix this?

**Comment by caneleex** [comment]
unfortunately, this is not descriptive enough. what stops working? loading segments for videos? the skip button for segments? submit/voting buttons? please be more specific

**Comment by Sneffel** [comment]
Sorry. Right. 
The button doesn't work. If I tap on it, nothing happens. It lights up but the operational buttons don't show up.

**Comment by caneleex** [comment]
this has been fixed already, however the fix will be out with the next vanced release which is not planned yet.
