### ISSUE TITLE
Are there plans to train some sort of automatic filter?

### ISSUE THREAD

**Issue by alita-moore** [YTVanced/SponsorBlock#52]
I'm guessing this would be very challenging / probably not worth it right now, but if there's a lot of time segment data can't you train a ML model to automatically label videos?

**Comment by caneleex** [comment]
there already was such project which is not active anymore - [NeuralBlock](https://github.com/andrewzlee/NeuralBlock).

also, this is a repository for the YouTube Vanced implementation of SponsorBlock. I suggest asking further questions on the [Discord server](https://discord.gg/sponsorblock)
